import PDFDocument from 'pdfkit';

export const generateReceiptPDF = (paymentData, memberData) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const chunks = [];

      doc.on('data', chunk => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Header
      doc.fontSize(20).text('Payment Receipt', { align: 'center' });
      doc.moveDown();

      // Member Info
      doc.fontSize(14).text(`Member: ${memberData.name}`);
      if (memberData.memberId) {
        doc.text(`Member ID: ${memberData.memberId}`);
      }
      if (memberData.contact) {
        doc.text(`Contact: ${memberData.contact}`);
      }
      doc.moveDown();

      // Payment Details
      doc.fontSize(12);
      doc.text(`Amount Paid: ${paymentData.amount}`);
      doc.text(`Payment Date: ${new Date(paymentData.date).toLocaleDateString()}`);
      doc.text(`Months Covered: ${paymentData.monthsCovered}`);
      doc.text(`Recorded By: ${paymentData.recordedBy}`);
      doc.moveDown();

      // Footer
      doc.fontSize(10).text(`Generated on: ${new Date().toLocaleString()}`, { align: 'center' });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

export const generateReceiptPDFFromReceipt = (receiptData, memberData) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ 
        margin: 50,
        size: 'A5' // Half A4 size
      });
      const chunks = [];

      doc.on('data', chunk => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Header with receipt number
      doc.fontSize(24).text('PAYMENT RECEIPT', { align: 'center' });
      doc.fontSize(12).text(`Receipt ID: ${receiptData.receiptId}`, { align: 'center' });
      doc.moveDown(1.5);

      // Payment details
      doc.fontSize(14).fillColor('#333333');
      doc.text('Payment Information:', { underline: true });
      doc.fontSize(12).fillColor('#000000');
      doc.moveDown(0.5);

      const details = [
        ['Payer Name:', receiptData.memberName],
        ['Member ID:', memberData.memberId || 'N/A'],
        ['Payment Amount:', `GHS ${receiptData.amount.toFixed(2)}`],
        ['Dues Per Month:', `GHS ${receiptData.duesPerMonth.toFixed(2)}`],
        ['Months Covered:', `${receiptData.monthsCovered} months`],
        ['Payment Date:', new Date(receiptData.paymentDate).toLocaleDateString('en-GB', { 
          day: 'numeric', 
          month: 'long', 
          year: 'numeric' 
        })],
        ['Recorded By:', receiptData.recordedBy],
        ['Recorded At:', new Date(receiptData.recordedAt).toLocaleString('en-GB')]
      ];

      details.forEach(([label, value]) => {
        doc.text(label, { continued: true, align: 'left' });
        doc.text(value, { align: 'left' });
      });

      if (receiptData.remarks) {
        doc.moveDown();
        doc.fontSize(12).text('Remarks:', { underline: true });
        doc.text(receiptData.remarks);
      }

      doc.moveDown(2);

      // Footer
      doc.fontSize(10).fillColor('#666666');
      doc.text('Thank you for your contribution!', { align: 'center' });
      doc.text('Generated by Dues Accountant', { align: 'center' });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

export const generateReportPDF = (reportData, title) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const chunks = [];

      doc.on('data', chunk => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      doc.fontSize(20).text(title, { align: 'center' });
      doc.moveDown();

      if (reportData.members) {
        doc.fontSize(14).text('Members Report');
        doc.moveDown();
        reportData.members.forEach((member, index) => {
          doc.fontSize(12).text(`${index + 1}. ${member.name} - Total Paid: ${member.totalPaid}`);
        });
      }

      if (reportData.payments) {
        doc.moveDown();
        doc.fontSize(14).text('Payments Report');
        doc.moveDown();
        reportData.payments.forEach((payment, index) => {
          doc.fontSize(12).text(`${index + 1}. ${payment.memberName} - ${payment.amount} on ${new Date(payment.date).toLocaleDateString()}`);
        });
      }

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

